/* Build a full Clash / Mihomo profile YAML from proxy URIs.
   Template aligned with mieru-panel: fake-ip DNS, CN/private DIRECT (split),
   or full tunnel (global). Client mode must be Rule. */

import { uriToClashYaml } from './yaml-convert'

/**
 * @param {{ name?: string, uri: string, protocol?: string }[]} items
 * @param {{ mode?: 'global'|'split', username?: string, brand?: string }} [opt]
 * @returns {{ yaml: string, count: number, skipped: number }}
 */
export function buildClashProfile(items, opt = {}) {
  const mode = opt.mode === 'global' ? 'global' : 'split'
  const user = (opt.username || 'user').trim() || 'user'
  const brand = (opt.brand || 'nft-panel').trim() || 'nft-panel'

  const proxies = []
  const names = []
  const seen = Object.create(null)
  let skipped = 0

  for (const it of items || []) {
    const uri = (it?.uri || '').trim()
    if (!uri) continue
    let name = (it.name || '').trim() || nameFromURI(uri) || 'proxy'
    const base = name
    if (seen[base]) {
      seen[base]++
      name = `${base}-${seen[base]}`
    } else {
      seen[base] = 1
    }
    const yml = uriToClashYaml(uri)
    if (!yml) {
      skipped++
      continue
    }
    const lines = yml.split('\n')
    if (lines[0] && lines[0].startsWith('- name:')) {
      lines[0] = `- name: "${esc(name)}"`
    }
    proxies.push(lines.join('\n'))
    names.push(name)
  }

  const L = []
  L.push(`# Mihomo / Clash Meta — generated by ${brand}`)
  L.push(`# user: ${user}`)
  if (mode === 'global') {
    L.push('# purpose: full tunnel · no China DIRECT · DNS via proxy path')
  } else {
    L.push('# routing: CN + private = DIRECT; foreign = PROXY')
  }
  L.push('# Import: Profiles → New → Remote (Clash Verge URL) or paste YAML')
  L.push('# Client mode must be 「规则 / Rule」 (not Global)')
  L.push('#')
  if (skipped > 0) {
    L.push(`# note: ${skipped} 条未写入 Clash（协议无法识别）`)
  }
  if (names.length === 0) {
    L.push('# warning: 当前列表没有 Clash 可识别节点（ss/vless/vmess/trojan/hy2/mieru）')
  }
  if (skipped > 0 || names.length === 0) L.push('#')

  L.push('mixed-port: 7890')
  L.push('allow-lan: false')
  L.push('mode: rule')
  L.push('log-level: info')
  L.push('ipv6: false')
  L.push('')
  L.push('dns:')
  L.push('  enable: true')
  L.push('  listen: 0.0.0.0:1053')
  L.push('  ipv6: false')
  L.push('  enhanced-mode: fake-ip')
  L.push('  fake-ip-range: 198.18.0.1/16')
  L.push('  fake-ip-filter:')
  L.push("    - '*.lan'")
  L.push("    - '*.local'")
  L.push('    - localhost')
  L.push("    - '+.msftconnecttest.com'")
  L.push("    - '+.msftncsi.com'")
  L.push("    - 'time.*.com'")
  L.push("    - 'time.*.gov'")
  L.push("    - 'time.*.apple.com'")
  L.push("    - 'ntp.*.com'")
  if (mode === 'global') {
    L.push('  nameserver:')
    L.push('    - https://1.1.1.1/dns-query')
    L.push('    - https://8.8.8.8/dns-query')
    L.push('    - 1.1.1.1')
    L.push('    - 8.8.8.8')
    L.push('  respect-rules: true')
  } else {
    L.push('  nameserver:')
    L.push('    - https://doh.pub/dns-query')
    L.push('    - https://dns.alidns.com/dns-query')
    L.push('    - 223.5.5.5')
    L.push('  fallback:')
    L.push('    - https://1.1.1.1/dns-query')
    L.push('    - https://8.8.8.8/dns-query')
    L.push('    - 1.1.1.1')
    L.push('    - 8.8.8.8')
    L.push('  fallback-filter:')
    L.push('    geoip: true')
    L.push('    geoip-code: CN')
    L.push('    ipcidr:')
    L.push('      - 240.0.0.0/4')
  }
  L.push('')
  L.push('proxies:')
  if (proxies.length === 0) {
    L.push('  []')
  } else {
    for (const p of proxies) {
      for (const line of p.split('\n')) {
        if (line === '') continue
        L.push(`  ${line}`)
      }
    }
  }
  L.push('')
  L.push('proxy-groups:')
  L.push('  - name: "PROXY"')
  L.push('    type: select')
  L.push('    proxies:')
  if (names.length === 0) {
    L.push('      - DIRECT')
  } else {
    for (const n of names) L.push(`      - ${yamlName(n)}`)
    L.push('      - DIRECT')
  }
  L.push('')
  L.push('rules:')
  L.push('  # local / private')
  L.push('  - GEOIP,PRIVATE,DIRECT,no-resolve')
  L.push('  - GEOSITE,private,DIRECT')
  if (mode === 'split') {
    L.push('  # China domains + IPs stay on domestic network')
    L.push('  - GEOSITE,cn,DIRECT')
    L.push('  - GEOIP,CN,DIRECT')
  }
  L.push('  # everything else via node')
  L.push('  - MATCH,PROXY')
  L.push('')

  return { yaml: L.join('\n'), count: names.length, skipped }
}

function nameFromURI(uri) {
  const h = uri.indexOf('#')
  if (h < 0) return ''
  try {
    return decodeURIComponent(uri.slice(h + 1))
  } catch {
    return uri.slice(h + 1)
  }
}

function esc(s) {
  return String(s || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function yamlName(n) {
  if (/^[A-Za-z0-9_.\-\u4e00-\u9fff]+$/.test(n)) return `"${esc(n)}"`
  return `"${esc(n)}"`
}

export function downloadTextFile(filename, text, mime = 'text/yaml;charset=utf-8') {
  const blob = new Blob([text], { type: mime })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(a.href), 2000)
}
