// Package subexport builds client subscription bodies (plain URI list,
// Clash/Mihomo YAML, Shadowrocket .conf) from panel share URIs.
package subexport

import (
	"encoding/base64"
	"fmt"
	"net/url"
	"strconv"
	"strings"
)

// Node is one exportable proxy entry.
type Node struct {
	Name     string // display name
	Protocol string // vless | shadowsocks | mieru
	URI      string
}

// Options control profile metadata.
type Options struct {
	Username string // for comments
	Panel    string // panel brand in comments
}

func (o Options) brand() string {
	if strings.TrimSpace(o.Panel) != "" {
		return strings.TrimSpace(o.Panel)
	}
	return "nft-panel"
}

// PlainBase64 returns standard base64 of newline-joined URIs (common client sub).
func PlainBase64(nodes []Node) string {
	var lines []string
	for _, n := range nodes {
		u := strings.TrimSpace(n.URI)
		if u == "" {
			continue
		}
		lines = append(lines, u)
	}
	raw := strings.Join(lines, "\n")
	if raw != "" {
		raw += "\n"
	}
	return base64.StdEncoding.EncodeToString([]byte(raw))
}

// PlainRaw returns newline-joined URIs without encoding.
func PlainRaw(nodes []Node) string {
	var lines []string
	for _, n := range nodes {
		u := strings.TrimSpace(n.URI)
		if u == "" {
			continue
		}
		lines = append(lines, u)
	}
	return strings.Join(lines, "\n") + "\n"
}

// ClashSplit builds Mihomo/Clash Meta YAML: CN + private DIRECT, else PROXY.
func ClashSplit(nodes []Node, opt Options) string {
	return buildClashYAML(nodes, opt, false)
}

// ClashGlobal builds full-tunnel anti-leak YAML (no China DIRECT).
func ClashGlobal(nodes []Node, opt Options) string {
	return buildClashYAML(nodes, opt, true)
}

func buildClashYAML(nodes []Node, opt Options, global bool) string {
	var b strings.Builder
	brand := opt.brand()
	user := strings.TrimSpace(opt.Username)
	if user == "" {
		user = "user"
	}

	if global {
		fmt.Fprintf(&b, "# Mihomo / Clash Meta – GLOBAL anti-leak (%s)\n", brand)
		fmt.Fprintf(&b, "# user: %s\n", user)
		b.WriteString("# purpose: full tunnel – no China DIRECT split\n")
		b.WriteString("# client: prefer Global mode; or Rule mode with rules below\n")
	} else {
		fmt.Fprintf(&b, "# Mihomo / Clash Meta – generated by %s\n", brand)
		fmt.Fprintf(&b, "# user: %s\n", user)
		b.WriteString("# routing: CN + private = DIRECT; foreign = PROXY\n")
		b.WriteString("# Import: Profiles → New → Remote (Clash Verge URL) or paste YAML\n")
		b.WriteString("# Client mode must be Rule (not Global)\n")
	}

	// Convert proxies; track names for groups.
	type proxyEntry struct {
		Name string
		YAML string
	}
	var proxies []proxyEntry
	var skipped int
	seen := map[string]int{}

	for _, n := range nodes {
		uri := strings.TrimSpace(n.URI)
		if uri == "" {
			continue
		}
		name := strings.TrimSpace(n.Name)
		if name == "" {
			name = nameFromURI(uri)
		}
		if name == "" {
			name = "proxy"
		}
		// unique names for Clash
		base := name
		if c := seen[base]; c > 0 {
			name = fmt.Sprintf("%s-%d", base, c+1)
		}
		seen[base]++

		yml := URIToClashProxy(uri, name)
		if yml == "" {
			skipped++
			continue
		}
		proxies = append(proxies, proxyEntry{Name: name, YAML: yml})
	}

	if skipped > 0 {
		fmt.Fprintf(&b, "# note: %d node(s) omitted (unsupported scheme)\n", skipped)
	}
	if len(proxies) == 0 {
		b.WriteString("# warning: no Clash-compatible proxies (vless/ss/mieru) in this subscription\n")
	}
	b.WriteString("#\n")

	b.WriteString("mixed-port: 7890\n")
	b.WriteString("allow-lan: false\n")
	b.WriteString("mode: rule\n")
	b.WriteString("log-level: info\n")
	b.WriteString("ipv6: false\n")
	b.WriteString("unified-delay: true\n")
	b.WriteString("tcp-concurrent: true\n")
	b.WriteString("\n")
	// Anti-DNS-leak: fake-ip + DoH + respect-rules so app DNS follows proxy rules.
	b.WriteString("dns:\n")
	b.WriteString("  enable: true\n")
	b.WriteString("  ipv6: false\n")
	b.WriteString("  enhanced-mode: fake-ip\n")
	b.WriteString("  fake-ip-range: 198.18.0.1/16\n")
	b.WriteString("  fake-ip-filter:\n")
	b.WriteString("    - \"*.lan\"\n")
	b.WriteString("    - \"*.local\"\n")
	b.WriteString("    - \"localhost.ptlogin2.qq.com\"\n")
	b.WriteString("  use-hosts: true\n")
	b.WriteString("  default-nameserver:\n")
	b.WriteString("    - 223.5.5.5\n")
	b.WriteString("    - 8.8.8.8\n")
	b.WriteString("  proxy-server-nameserver:\n")
	b.WriteString("    - https://dns.alidns.com/dns-query\n")
	b.WriteString("    - https://doh.pub/dns-query\n")
	if global {
		b.WriteString("  nameserver:\n")
		b.WriteString("    - https://1.1.1.1/dns-query\n")
		b.WriteString("    - https://8.8.8.8/dns-query\n")
		b.WriteString("  respect-rules: true\n")
	} else {
		b.WriteString("  nameserver:\n")
		b.WriteString("    - https://dns.alidns.com/dns-query\n")
		b.WriteString("    - https://doh.pub/dns-query\n")
		b.WriteString("  fallback:\n")
		b.WriteString("    - https://1.1.1.1/dns-query\n")
		b.WriteString("    - https://8.8.8.8/dns-query\n")
		b.WriteString("  fallback-filter:\n")
		b.WriteString("    geoip: true\n")
		b.WriteString("    geoip-code: CN\n")
		b.WriteString("  respect-rules: true\n")
	}
	b.WriteString("\n")
	b.WriteString("proxies:\n")
	if len(proxies) == 0 {
		b.WriteString("  []\n")
	} else {
		for _, p := range proxies {
			// URIToClashProxy returns lines starting with "- name:"
			for _, line := range strings.Split(p.YAML, "\n") {
				if line == "" {
					continue
				}
				b.WriteString("  ")
				b.WriteString(line)
				b.WriteByte('\n')
			}
		}
	}

	// proxy names list
	var names []string
	for _, p := range proxies {
		names = append(names, p.Name)
	}

	b.WriteString("\nproxy-groups:\n")
	b.WriteString("  - name: PROXY\n")
	b.WriteString("    type: select\n")
	b.WriteString("    proxies:\n")
	if len(names) == 0 {
		b.WriteString("      - DIRECT\n")
	} else {
		for _, n := range names {
			fmt.Fprintf(&b, "      - %s\n", yamlQuoteIfNeeded(n))
		}
		b.WriteString("      - AUTO\n")
		b.WriteString("      - DIRECT\n")
	}
	if len(names) > 0 {
		b.WriteString("  - name: AUTO\n")
		b.WriteString("    type: url-test\n")
		b.WriteString("    url: http://www.gstatic.com/generate_204\n")
		b.WriteString("    interval: 300\n")
		b.WriteString("    tolerance: 50\n")
		b.WriteString("    proxies:\n")
		for _, n := range names {
			fmt.Fprintf(&b, "      - %s\n", yamlQuoteIfNeeded(n))
		}
	}

	b.WriteString("\nrules:\n")
	b.WriteString("  - DOMAIN-SUFFIX,local,DIRECT\n")
	b.WriteString("  - DOMAIN-SUFFIX,localhost,DIRECT\n")
	b.WriteString("  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve\n")
	b.WriteString("  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve\n")
	b.WriteString("  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve\n")
	b.WriteString("  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve\n")
	b.WriteString("  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve\n")
	b.WriteString("  - GEOIP,PRIVATE,DIRECT,no-resolve\n")
	if global {
		b.WriteString("  - MATCH,PROXY\n")
	} else {
		b.WriteString("  - GEOIP,CN,DIRECT\n")
		b.WriteString("  - MATCH,PROXY\n")
	}
	return b.String()
}

// ShadowrocketConf builds a native .conf with anti-leak defaults.
func ShadowrocketConf(nodes []Node, opt Options) string {
	var b strings.Builder
	brand := opt.brand()
	user := strings.TrimSpace(opt.Username)
	if user == "" {
		user = "user"
	}

	fmt.Fprintf(&b, "#!name=%s 全局防泄漏\n", brand)
	fmt.Fprintf(&b, "#!desc=全面防泄漏 · 无国内直连 · DNS走代理 · 关IPv6 · user=%s\n", user)
	fmt.Fprintf(&b, "#!category=%s\n", brand)
	fmt.Fprintf(&b, "# Generated by %s – Shadowrocket native .conf\n", brand)
	b.WriteString("# 用法: 配置 → 从 URL 下载 / 导入此链接 → 勾选使用 → 首页选节点开全局或配置模式\n")
	b.WriteString("# 勿与 default.conf 那套国内 DIRECT 规则混用\n")
	b.WriteString("#\n")

	b.WriteString("[General]\n")
	b.WriteString("bypass-system = true\n")
	b.WriteString("skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local\n")
	b.WriteString("tun-excluded-routes = 10.0.0.0/8,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16\n")
	b.WriteString("dns-server = 1.1.1.1,8.8.8.8\n")
	b.WriteString("fallback-dns-server = system\n")
	b.WriteString("ipv6 = false\n")
	b.WriteString("prefer-ipv6 = false\n")
	b.WriteString("dns-direct-system = false\n")
	b.WriteString("icmp-auto-reply = true\n")
	b.WriteString("always-reject-url-rewrite = false\n")
	b.WriteString("private-ip-answer = true\n")
	b.WriteString("dns-direct-fallback-proxy = true\n")
	b.WriteString("\n")

	b.WriteString("[Proxy]\n")
	b.WriteString("DIRECT = direct\n")
	var proxyNames []string
	var skippedMieru int
	seen := map[string]int{}
	for _, n := range nodes {
		uri := strings.TrimSpace(n.URI)
		if uri == "" {
			continue
		}
		proto := strings.ToLower(strings.TrimSpace(n.Protocol))
		if proto == "mieru" || strings.HasPrefix(strings.ToLower(uri), "mierus://") {
			skippedMieru++
			continue
		}
		name := strings.TrimSpace(n.Name)
		if name == "" {
			name = nameFromURI(uri)
		}
		if name == "" {
			name = "proxy"
		}
		base := name
		if c := seen[base]; c > 0 {
			name = fmt.Sprintf("%s-%d", base, c+1)
		}
		seen[base]++
		line := URIToShadowrocketLine(uri, name)
		if line == "" {
			continue
		}
		b.WriteString(line)
		b.WriteByte('\n')
		proxyNames = append(proxyNames, name)
	}
	if skippedMieru > 0 {
		fmt.Fprintf(&b, "# %d mieru node(s) skipped – import plain sub for mierus://\n", skippedMieru)
	}
	if len(proxyNames) == 0 {
		b.WriteString("# no vless/ss proxies available\n")
	}

	b.WriteString("\n[Proxy Group]\n")
	if len(proxyNames) > 0 {
		b.WriteString("Proxy = select, ")
		b.WriteString(strings.Join(proxyNames, ", "))
		b.WriteString(", DIRECT\n")
	} else {
		b.WriteString("Proxy = select, DIRECT\n")
	}

	b.WriteString("\n[Rule]\n")
	// LAN only direct; everything else proxy (anti-leak)
	b.WriteString("IP-CIDR,127.0.0.0/8,DIRECT\n")
	b.WriteString("IP-CIDR,10.0.0.0/8,DIRECT\n")
	b.WriteString("IP-CIDR,172.16.0.0/12,DIRECT\n")
	b.WriteString("IP-CIDR,192.168.0.0/16,DIRECT\n")
	b.WriteString("IP-CIDR,169.254.0.0/16,DIRECT\n")
	b.WriteString("GEOIP,PRIVATE,DIRECT\n")
	b.WriteString("FINAL,Proxy\n")
	return b.String()
}

func nameFromURI(uri string) string {
	i := strings.Index(uri, "#")
	if i < 0 {
		return ""
	}
	frag, err := url.QueryUnescape(uri[i+1:])
	if err != nil {
		return uri[i+1:]
	}
	return frag
}

func yamlQuoteIfNeeded(s string) string {
	if s == "" {
		return `""`
	}
	// Quote if special chars
	if strings.ContainsAny(s, `:{}[],&*?#|>!%@'" \t`) || strings.Contains(s, "·") {
		return strconv.Quote(s)
	}
	return s
}
